fieldtest:
	g++ fieldclasstest.cpp -o fieldclasstest.o -std=c++11

dimmaptest:
	g++ dimmaptest.cpp -o dimmaptest.o -std=c++11			

map_fulltest1:
	g++ map1d4d_full4d_test1.cpp -o maptest1.o -std=c++11

derivativetest:
	g++ derivtest.cpp derivatives.cpp -o derivtest.o -std=c++11;
